version: '3.8'

services:
  postgres-spatial:
    image: postgis/postgis:14-3.3-alpine
    container_name: postgres_spatial_sipma
    environment:
      POSTGRES_DB: sipma_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata_spatial:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sipma_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata_spatial: