// Mock data — Acervo Patrimonial do Maranhão
//
// Coordinate convention:
//   • `latitude`, `longitude`  = real-world geographic coordinates (informative).
//   • `mapX`, `mapY`           = position inside the simplified SVG silhouette
//                                (viewBox 0..90, 0..95). Hand-calibrated so pins
//                                fall correctly inside the outline — the SVG is a
//                                stylised contour and is not a true projection,
//                                so a pure lat/lng→x/y formula is not enough.
//
// `components.jsx` exposes a `projectToMAViewBox(latitude, longitude)` utility
// that returns a best-effort linear projection for new entries; for production
// pins we prefer the hand-calibrated mapX/mapY values.

window.MUNICIPIOS = [
  "São Luís", "Alcântara", "Caxias", "Viana", "Codó", "Carolina",
  "Cururupu", "Rosário", "Guimarães", "Pinheiro", "Coroatá", "Tutóia",
  "Imperatriz", "Balsas", "Bacabal", "Itapecuru-Mirim", "Barra do Corda", "Timon",
];

// Reference table of municipality coordinates — used both for documentation and
// as a fallback when a record lacks explicit mapX/mapY.
window.MA_MUN_COORDS = {
  "São Luís":         { latitude: -2.5307, longitude: -44.3068, mapX: 48.5, mapY: 19.5 },
  "Alcântara":        { latitude: -2.4041, longitude: -44.4167, mapX: 43, mapY: 18.5 },
  "Caxias":           { latitude: -4.8589, longitude: -43.3561, mapX: 59, mapY: 38.5 },
  "Viana":            { latitude: -3.2203, longitude: -45.0038, mapX: 42, mapY: 24.5 },
  "Cururupu":         { latitude: -1.8283, longitude: -44.8683, mapX: 36.5, mapY: 17.5 },
  "Carolina":         { latitude: -7.3358, longitude: -47.4719, mapX: 35, mapY: 80 },
  "Itapecuru-Mirim":  { latitude: -3.3925, longitude: -44.3586, mapX: 51, mapY: 26 },
  "Pinheiro":         { latitude: -2.5222, longitude: -45.0789, mapX: 38.5, mapY: 22 },
  "Codó":             { latitude: -4.4556, longitude: -43.8856, mapX: 54.5, mapY: 33.5 },
  "Timon":            { latitude: -5.095, longitude: -42.8364, mapX: 63.5, mapY: 41 },
  "Tutóia":           { latitude: -2.7619, longitude: -42.2744, mapX: 63, mapY: 17 },
  "Balsas":           { latitude: -7.5321, longitude: -46.0372, mapX: 44, mapY: 67 },
  "Imperatriz":       { latitude: -5.5264, longitude: -47.4919, mapX: 30.5, mapY: 59 },
  "Barra do Corda":   { latitude: -5.5069, longitude: -45.2433, mapX: 43, mapY: 46.5 },
  "Bacabal":          { latitude: -4.225, longitude: -44.7833, mapX: 44, mapY: 33.5 },
  "Rosário":          { latitude: -2.9344, longitude: -44.2531, mapX: 50.5, mapY: 22 },
  "Guimarães":        { latitude: -2.1328, longitude: -44.6008, mapX: 40, mapY: 16.5 },
  "Coroatá":          { latitude: -4.1308, longitude: -44.1242, mapX: 53, mapY: 31.5 },
};

// Helper used when seeding records below.
function _c(mun) { return window.MA_MUN_COORDS[mun] || { latitude: null, longitude: null, mapX: null, mapY: null }; }

// ====================================================================
// Image library — Wikimedia Commons (domínio público / CC-BY) — usadas
// como placeholders fotográficos contextualizados ao patrimônio
// maranhense. Substituem os blocos puramente textuais antes utilizados.
// ====================================================================
window.IMG = {
  // São Luís — Centro Histórico / Praia Grande / casario azulejado
  slz_afonso_pena:  "https://upload.wikimedia.org/wikipedia/commons/0/0a/R._Afonso_Pena_112_-_Centro_SLZ_%283%29.jpg",
  slz_nazare:       "https://upload.wikimedia.org/wikipedia/commons/3/39/R._de_Nazar%C3%A9_365_-_Centro_SLZ_%282%29.jpg",
  slz_saude:        "https://upload.wikimedia.org/wikipedia/commons/6/64/R._da_Sa%C3%BAde_221_-_Centro_SLZ_%285%29.jpg",
  slz_centro:       "https://upload.wikimedia.org/wikipedia/commons/3/3c/Centro_Hist%C3%B3rico_de_S%C3%A3o_Lu%C3%ADs%2C_Maranh%C3%A3o%2C_Brasil_2.jpg",
  // Alcântara — museus e ruínas
  alc_museu_01:     "https://upload.wikimedia.org/wikipedia/commons/7/72/Mar2024._Museu_Casa_Hist%C3%B3rica_de_Alc%C3%A2ntara%2C_Maranh%C3%A3o%2C_Brazil_01.jpg",
  alc_museu_fach:   "https://upload.wikimedia.org/wikipedia/commons/2/21/Fachada_do_Museu_Casa_Hist%C3%B3rica_de_Alc%C3%A2ntara%2C_Maranh%C3%A3o%2C_2015..jpg",
  alc_museu_ma:     "https://upload.wikimedia.org/wikipedia/commons/4/40/Museu_Casa_Hist%C3%B3rica_de_Alc%C3%A2ntara%2C_Alc%C3%A2ntara%2C_MA.jpg",
  alc_ruinas:       "https://upload.wikimedia.org/wikipedia/commons/8/84/Ruinas_de_Alc%C3%A2ntara.jpg",
  alc_sao_matias:   "https://upload.wikimedia.org/wikipedia/commons/f/f5/Ruinas_Igreja_Sao_Matias_Alc%C3%A2ntara_MA.jpg",
  // Tambor de Crioula — patrimônio imaterial
  tc_coreiras:      "https://upload.wikimedia.org/wikipedia/commons/3/3a/Coreiras_de_tambor_de_crioula.png",
  tc_casa:          "https://upload.wikimedia.org/wikipedia/commons/d/d5/Casa_do_Tambor_de_Crioula_-_01.jpg",
  tc_feirinha:      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Tambor_de_Crioula_na_Feirinha_-_S%C3%A3o_Lu%C3%ADs%2C_Maranh%C3%A3o_05.jpg",
  tc_0137:          "https://upload.wikimedia.org/wikipedia/commons/0/09/Tambor_de_Crioula_do_Maranh%C3%A3o_-_0137.jpg",
};

window.IMOVEIS = [
  {
    id: "APM-0142",
    nome: "Casarão Colonial da Praia Grande",
    municipio: "São Luís",
    bairro: "Centro Histórico — Praia Grande",
    endereco: "Rua Portugal, 187",
    tipo: "Casarão",
    tipologia: "Sobrado luso-brasileiro azulejado",
    pavimentos: 3,
    comodos: 14,
    matricula: "12.487 / 1ª CRI",
    uso_orig: "Residencial e comercial",
    uso_atual: "Cultural — espaço expositivo",
    publico: "Público",
    orgao: "IPHAN — Inst. do Patrimônio",
    esfera: "Federal",
    iphan_link: "iphan.gov.br/processos/12487",
    judicial: false,
    situacao: "preservado",
    risco: "Baixo",
    construcao: "c. 1820",
    tombamento_ano: "1955",
    vistoria: "12 Mar 2026",
    ..._c("São Luís"),
    // Slightly offset so the three São Luís pins don't overlap.
    mapX: 49.0, mapY: 19.0,
    img: "Fachada azulejada de 3 pavimentos — Praia Grande",
    imgUrl: window.IMG.slz_afonso_pena,
    gallery: [
      { url: window.IMG.slz_afonso_pena, label: "Fachada principal · Rua Portugal, Praia Grande" },
      { url: window.IMG.slz_centro,      label: "Vista do conjunto urbano · Centro Histórico de São Luís" },
      { url: window.IMG.slz_saude,       label: "Detalhe · azulejaria portuguesa biscoito" },
      { url: window.IMG.slz_nazare,      label: "Casario lindeiro · Rua de Nazaré" },
    ],
    historico: "Edificação representativa do ciclo do algodão maranhense, ergueu-se entre 1815 e 1822 nas proximidades do antigo porto da Praia Grande. Apresenta cinco janelas em arco abatido por pavimento e revestimento integral em azulejos portugueses biscoito, dispostos em padrão de damas. Serviu como residência da família Ribeiro Pinto até 1923, quando foi convertido em armazém de fumo. Restaurado entre 2008 e 2011 pelo programa Monumenta. Hoje abriga exposições permanentes do acervo fotográfico do IPHAN-MA.",
  },
  {
    id: "APM-0287",
    nome: "Sobrado Histórico do Centro",
    municipio: "São Luís",
    bairro: "Desterro",
    endereco: "Largo do Desterro, 42",
    tipo: "Sobrado",
    tipologia: "Sobrado eclético",
    pavimentos: 2,
    comodos: 9,
    matricula: "8.211 / 2ª CRI",
    uso_orig: "Residencial",
    uso_atual: "Vago",
    publico: "Privado",
    orgao: "IPHAN-MA",
    esfera: "Federal e estadual",
    iphan_link: "iphan.gov.br/processos/8211",
    judicial: true,
    situacao: "atencao",
    risco: "Médio",
    construcao: "c. 1865",
    tombamento_ano: "1974",
    vistoria: "04 Nov 2025",
    ..._c("São Luís"),
    mapX: 48.0, mapY: 20.0,
    img: "Sobrado eclético, sacada de ferro fundido",
    imgUrl: window.IMG.slz_nazare,
    gallery: [
      { url: window.IMG.slz_nazare,      label: "Fachada · Rua de Nazaré, Centro de São Luís" },
      { url: window.IMG.slz_saude,       label: "Sobrado vizinho · Rua da Saúde" },
      { url: window.IMG.slz_centro,      label: "Contexto urbano · Centro Histórico" },
    ],
    historico: "Sobrado de feição eclética com elementos neoclássicos no térreo e art-nouveau na cimalha, característico da fase tardia do casario do Desterro.",
  },
  {
    id: "APM-0319",
    nome: "Solar Antigo de Alcântara",
    municipio: "Alcântara",
    bairro: "Rua Grande",
    endereco: "Rua Grande, s/nº",
    tipo: "Solar",
    tipologia: "Solar setecentista",
    pavimentos: 2,
    comodos: 18,
    matricula: "1.044 / Alcântara",
    uso_orig: "Residencial — engenho",
    uso_atual: "Ruína estabilizada",
    publico: "Público",
    orgao: "IPHAN",
    esfera: "Federal",
    iphan_link: "iphan.gov.br/processos/1044",
    judicial: false,
    situacao: "risco",
    risco: "Alto",
    construcao: "c. 1750",
    tombamento_ano: "1948",
    vistoria: "Pendente — última 2022",
    ..._c("Alcântara"),
    mapX: 42.5, mapY: 18.5,
    img: "Frontispício setecentista — Alcântara",
    imgUrl: window.IMG.alc_ruinas,
    gallery: [
      { url: window.IMG.alc_ruinas,      label: "Ruína estabilizada · Solar setecentista de Alcântara" },
      { url: window.IMG.alc_sao_matias,  label: "Conjunto urbano · Ruínas da Igreja de São Matias" },
      { url: window.IMG.alc_museu_ma,    label: "Casario lindeiro · centro histórico de Alcântara" },
    ],
    historico: "Um dos remanescentes mais íntegros da arquitetura senhorial do ciclo açucareiro no Maranhão. Estabilizado pelo IPHAN em 1998 após colapso parcial da empena leste.",
  },
  {
    id: "APM-0408",
    nome: "Imóvel Tombado de Caxias",
    municipio: "Caxias",
    bairro: "Centro",
    endereco: "Praça Gonçalves Dias, 12",
    tipo: "Casa térrea",
    tipologia: "Casa térrea oitocentista",
    pavimentos: 1,
    comodos: 7,
    matricula: "5.708 / Caxias",
    uso_orig: "Residencial",
    uso_atual: "Museu municipal",
    publico: "Público",
    orgao: "IPHAN-MA",
    esfera: "Estadual",
    iphan_link: "—",
    judicial: false,
    situacao: "restaurado",
    risco: "Baixo",
    construcao: "c. 1844",
    tombamento_ano: "1989",
    vistoria: "02 Fev 2026",
    ..._c("Caxias"),
    img: "Casa térrea — fachada cor terra",
    imgUrl: window.IMG.alc_museu_ma,
    gallery: [
      { url: window.IMG.alc_museu_ma,    label: "Fachada · casa térrea oitocentista" },
      { url: window.IMG.alc_museu_fach,  label: "Frontispício e platibanda" },
    ],
    historico: "Residência onde Gonçalves Dias passou a infância. Convertida em museu pelo município em 1989, restaurada em 2017.",
  },
  {
    id: "APM-0512",
    nome: "Antigo Engenho de Viana",
    municipio: "Viana",
    bairro: "Zona rural — Pindobal",
    endereco: "Estrada do Engenho, km 7",
    tipo: "Conjunto rural",
    tipologia: "Engenho — casa-grande e capela",
    pavimentos: 1,
    comodos: 12,
    matricula: "3.119 / Viana",
    uso_orig: "Produção açucareira",
    uso_atual: "Abandonado",
    publico: "Privado",
    orgao: "Sem tombamento",
    esfera: "—",
    iphan_link: "—",
    judicial: true,
    situacao: "risco",
    risco: "Crítico",
    construcao: "c. 1790",
    tombamento_ano: "Em processo",
    vistoria: "Vencida",
    ..._c("Viana"),
    img: "Casa-grande em ruínas — Viana",
    imgUrl: window.IMG.alc_sao_matias,
    gallery: [
      { url: window.IMG.alc_sao_matias,  label: "Remanescentes da casa-grande · Engenho de Viana" },
      { url: window.IMG.alc_ruinas,      label: "Conjunto rural em ruína estabilizada" },
    ],
    historico: "Conjunto rural com casa-grande, capela e remanescentes de senzala. Processo de tombamento aberto em 2019.",
  },
  {
    id: "APM-0644",
    nome: "Casa de Câmara e Cadeia",
    municipio: "Alcântara",
    bairro: "Praça Matriz",
    endereco: "Praça da Matriz, s/nº",
    tipo: "Edifício público",
    tipologia: "Câmara colonial",
    pavimentos: 2,
    comodos: 11,
    matricula: "1.022 / Alcântara",
    uso_orig: "Câmara e cadeia",
    uso_atual: "Centro de visitantes",
    publico: "Público",
    orgao: "IPHAN",
    esfera: "Federal",
    iphan_link: "iphan.gov.br/processos/1022",
    judicial: false,
    situacao: "preservado",
    risco: "Baixo",
    construcao: "c. 1747",
    tombamento_ano: "1948",
    vistoria: "20 Jan 2026",
    ..._c("Alcântara"),
    mapX: 43.5, mapY: 19.5,
    img: "Câmara colonial — Alcântara",
    imgUrl: window.IMG.alc_museu_fach,
    gallery: [
      { url: window.IMG.alc_museu_fach,  label: "Frontispício · Casa de Câmara e Cadeia" },
      { url: window.IMG.alc_museu_01,    label: "Vista lateral · Praça da Matriz" },
      { url: window.IMG.alc_museu_ma,    label: "Conjunto urbano · Alcântara" },
    ],
    historico: "Sede da antiga vila colonial, importante exemplar civil do século XVIII.",
  },
  {
    id: "APM-0701",
    nome: "Sobrado dos Azulejos",
    municipio: "São Luís",
    bairro: "Praia Grande",
    endereco: "Rua da Estrela, 64",
    tipo: "Sobrado",
    tipologia: "Sobrado azulejado",
    pavimentos: 3,
    comodos: 16,
    matricula: "12.502 / 1ª CRI",
    uso_orig: "Residencial e comercial",
    uso_atual: "Hotel boutique",
    publico: "Privado",
    orgao: "IPHAN",
    esfera: "Federal",
    iphan_link: "iphan.gov.br/processos/12502",
    judicial: false,
    situacao: "restaurado",
    risco: "Baixo",
    construcao: "c. 1850",
    tombamento_ano: "1974",
    vistoria: "08 Out 2025",
    ..._c("São Luís"),
    mapX: 50.0, mapY: 20.5,
    img: "Sobrado azulejado azul-cobalto",
    imgUrl: window.IMG.slz_saude,
    gallery: [
      { url: window.IMG.slz_saude,       label: "Fachada azulejada · Rua da Estrela" },
      { url: window.IMG.slz_afonso_pena, label: "Sobrado lindeiro · Rua Afonso Pena" },
      { url: window.IMG.slz_centro,      label: "Centro Histórico de São Luís" },
    ],
    historico: "Restauração premiada em 2014, mantendo painel original de azulejos portugueses no térreo.",
  },
  {
    id: "APM-0822",
    nome: "Igreja Matriz de Cururupu",
    municipio: "Cururupu",
    bairro: "Centro",
    endereco: "Praça da Matriz",
    tipo: "Edifício religioso",
    tipologia: "Igreja oitocentista",
    pavimentos: 1,
    comodos: 5,
    matricula: "—",
    uso_orig: "Religioso",
    uso_atual: "Religioso",
    publico: "Privado",
    orgao: "IPHAN-MA",
    esfera: "Estadual",
    iphan_link: "—",
    judicial: false,
    situacao: "atencao",
    risco: "Médio",
    construcao: "c. 1872",
    tombamento_ano: "1996",
    vistoria: "Pendente",
    ..._c("Cururupu"),
    img: "Igreja de cal e óleo de baleia",
    imgUrl: window.IMG.alc_sao_matias,
    gallery: [
      { url: window.IMG.alc_sao_matias,  label: "Frontispício · igreja oitocentista" },
      { url: window.IMG.alc_ruinas,      label: "Conjunto religioso histórico" },
    ],
    historico: "Construída em alvenaria de pedra e cal de óleo de baleia, técnica típica do litoral norte maranhense.",
  },
  {
    id: "APM-0915",
    nome: "Quintal de Carolina",
    municipio: "Carolina",
    bairro: "Centro",
    endereco: "Rua do Comércio, 220",
    tipo: "Casa térrea",
    tipologia: "Casa de varanda corrida",
    pavimentos: 1,
    comodos: 6,
    matricula: "4.401 / Carolina",
    uso_orig: "Residencial",
    uso_atual: "Residencial",
    publico: "Privado",
    orgao: "Município",
    esfera: "Municipal",
    iphan_link: "—",
    judicial: false,
    situacao: "semvist",
    risco: "Desconhecido",
    construcao: "c. 1910",
    tombamento_ano: "2008",
    vistoria: "Sem registro recente",
    ..._c("Carolina"),
    img: "Casa de varanda — interior do Maranhão",
    imgUrl: window.IMG.alc_museu_ma,
    gallery: [
      { url: window.IMG.alc_museu_ma,    label: "Casa de varanda corrida — exemplar tardio" },
      { url: window.IMG.alc_museu_fach,  label: "Frontispício · detalhe construtivo" },
    ],
    historico: "Exemplar tardio com varanda corrida típica do sertão maranhense durante o ciclo da borracha do Tocantins.",
  },
];

window.IMATERIAL = [
  { id: "IMT-001", nome: "Bumba-meu-boi do Maranhão", municipio: "São Luís e Baixada", categoria: "Festa popular", regiao: "Estadual", status: "Reconhecido — UNESCO 2019", resumo: "Manifestação cultural complexa que reúne música, dança, teatro e religiosidade em torno do ciclo do boi.", img: "Sotaque de zabumba — Bumba-meu-boi", imgUrl: window.IMG.tc_feirinha },
  { id: "IMT-002", nome: "Tambor de Crioula", municipio: "Estadual", categoria: "Dança e canto", regiao: "Estadual", status: "Reconhecido — IPHAN 2007", resumo: "Roda de tambores, canto e dança praticada por afrodescendentes, com forte presença em São Luís e Cururupu.", img: "Tambores de crioula", imgUrl: window.IMG.tc_casa, gallery: [window.IMG.tc_casa, window.IMG.tc_coreiras, window.IMG.tc_feirinha, window.IMG.tc_0137] },
  { id: "IMT-003", nome: "Festa do Divino Espírito Santo", municipio: "Alcântara", categoria: "Manifestação religiosa", regiao: "Litoral", status: "Reconhecido — IPHAN 2016", resumo: "Festa centenária com tribuna, caixeiras e cortejo do Imperador, particularmente intensa em Alcântara.", img: "Caixeiras do Divino", imgUrl: window.IMG.alc_museu_01 },
  { id: "IMT-004", nome: "Cacuriá", municipio: "São Luís", categoria: "Dança popular", regiao: "Capital", status: "Em registro", resumo: "Dança de roda derivada das festas do Divino, marcada por gestos sensuais e cantos de improviso.", img: "Cacuriá — roda de dança", imgUrl: window.IMG.tc_coreiras },
  { id: "IMT-005", nome: "Reggae Maranhense", municipio: "São Luís", categoria: "Música e dança urbana", regiao: "Capital", status: "Reconhecido — Estado 2018", resumo: "Apropriação maranhense do reggae jamaicano, com radiolas, dançarinos e identidade urbana própria.", img: "Radiola de reggae", imgUrl: window.IMG.slz_centro },
  { id: "IMT-006", nome: "Saber da Cerâmica de Itamatatiua", municipio: "Alcântara", categoria: "Saber tradicional", regiao: "Quilombola", status: "Em estudo", resumo: "Modo de fazer cerâmica utilitária de matriz africana, preservado pela comunidade quilombola de Itamatatiua.", img: "Cerâmica de Itamatatiua", imgUrl: window.IMG.tc_0137 },
];

window.ARQUEOLOGICOS = [
  { id: "SAR-014", nome: "Sítio Arqueológico de Alcântara", municipio: "Alcântara",       tipo: "Pré-colonial — sambaquis",          protecao: "Restrito", acesso: "Acesso parcial — coords protegidas", resumo: "Conjunto de sambaquis em margem estuarina com ocupação datada entre 2.500 e 800 AP.", restrito: true,  imgUrl: null,                  ..._c("Alcântara"),       mapX: 41, mapY: 19 },
  { id: "SAR-022", nome: "Engenho Soberano",               municipio: "Itapecuru-Mirim",  tipo: "Histórico — engenho colonial",      protecao: "Aberto",   acesso: "Visita guiada",                       resumo: "Remanescente de engenho do século XVIII com moenda, capela e senzala parcialmente preservados.", restrito: false, imgUrl: window.IMG.alc_sao_matias, ..._c("Itapecuru-Mirim") },
  { id: "SAR-031", nome: "Lajeado das Pedras Pintadas",    municipio: "Carolina",         tipo: "Pré-colonial — arte rupestre",      protecao: "Restrito", acesso: "Coordenadas ocultas",                 resumo: "Painel rupestre com mais de 80 grafismos zoomorfos e geométricos atribuídos a populações ceramistas.", restrito: true,  imgUrl: null,                  ..._c("Carolina"),        mapX: 32, mapY: 78 },
  { id: "SAR-040", nome: "Sítio Quilombola de Itamatatiua", municipio: "Alcântara",       tipo: "Histórico — quilombo",              protecao: "Aberto",   acesso: "Visita guiada — comunidade",          resumo: "Remanescentes arqueológicos associados à formação do quilombo de Itamatatiua.", restrito: false, imgUrl: window.IMG.alc_ruinas,     ..._c("Alcântara"),       mapX: 40, mapY: 21 },
];

window.VISTORIAS = [
  { id: "V-2026-118", imovel: "APM-0142", imovelNome: "Casarão Colonial da Praia Grande", data: "12 Mar 2026", responsavel: "Arq. Helena Borba", orgao: "IPHAN-MA", status: "Realizada", risco: "Baixo", resumo: "Verificação anual da estrutura e dos azulejos do térreo." },
  { id: "V-2026-117", imovel: "APM-0408", imovelNome: "Imóvel Tombado de Caxias", data: "02 Fev 2026", responsavel: "Eng. Cleber Pinheiro", orgao: "IPHAN-MA", status: "Realizada", risco: "Baixo", resumo: "Inspeção pós-restauro, sistema elétrico e cobertura." },
  { id: "V-2026-116", imovel: "APM-0644", imovelNome: "Casa de Câmara e Cadeia", data: "20 Jan 2026", responsavel: "Arq. Helena Borba", orgao: "IPHAN-MA", status: "Realizada", risco: "Baixo", resumo: "Vistoria de rotina, sem ocorrências." },
  { id: "V-2026-115", imovel: "APM-0287", imovelNome: "Sobrado Histórico do Centro", data: "—", responsavel: "Arq. Marina Lobato", orgao: "IPHAN-MA", status: "Em análise", risco: "Médio", resumo: "Necessária reavaliação por suspeita de infiltração na empena oeste." },
  { id: "V-2026-114", imovel: "APM-0319", imovelNome: "Solar Antigo de Alcântara", data: "—", responsavel: "—", orgao: "IPHAN-MA", status: "Pendente", risco: "Alto", resumo: "Última vistoria em 2022 — necessidade urgente de retorno." },
  { id: "V-2026-113", imovel: "APM-0512", imovelNome: "Antigo Engenho de Viana", data: "—", responsavel: "—", orgao: "IPHAN-MA", status: "Vencida", risco: "Crítico", resumo: "Vistoria vencida há 14 meses. Risco estrutural elevado." },
  { id: "V-2026-112", imovel: "APM-0822", imovelNome: "Igreja Matriz de Cururupu", data: "—", responsavel: "Arq. Marina Lobato", orgao: "IPHAN-MA", status: "Pendente", risco: "Médio", resumo: "Agendar inspeção de cobertura antes do período chuvoso." },
];

window.USUARIOS = [
  { nome: "Helena Borba", email: "helena.borba@iphan.gov.br", perfil: "Administrador geral", orgao: "IPHAN-MA", status: "Ativo", ult: "Hoje, 09:21" },
  { nome: "Cleber Pinheiro", email: "cleber.pinheiro@cultura.ma.gov.br", perfil: "Técnico patrimonial", orgao: "IPHAN-MA", status: "Ativo", ult: "Ontem, 17:08" },
  { nome: "Marina Lobato", email: "marina.lobato@iphan.gov.br", perfil: "Técnico patrimonial", orgao: "IPHAN-MA", status: "Ativo", ult: "Há 2 dias" },
  { nome: "Roberto Andrade", email: "r.andrade@ufma.br", perfil: "Consultor", orgao: "UFMA", status: "Ativo", ult: "Há 5 dias" },
  { nome: "Patrícia Sales", email: "patricia@condephaat.ma.gov.br", perfil: "Leitor institucional", orgao: "Município de Caxias", status: "Inativo", ult: "Há 1 mês" },
  { nome: "Júlio Ramos", email: "julio.ramos@iphan.gov.br", perfil: "Técnico patrimonial", orgao: "IPHAN-MA", status: "Ativo", ult: "Hoje, 08:42" },
];

window.ALERTAS = [
  { tipo: "risco", titulo: "Risco estrutural crítico — Antigo Engenho de Viana", sub: "APM-0512 · Vistoria vencida há 14 meses", data: "Há 3 dias" },
  { tipo: "judicial", titulo: "Nova ação judicial registrada", sub: "Sobrado Histórico do Centro — APM-0287", data: "Há 1 semana" },
  { tipo: "vistoria", titulo: "5 vistorias vencerão neste mês", sub: "Conferir agenda de campo", data: "Há 1 dia" },
  { tipo: "tombamento", titulo: "Processo de tombamento avançou", sub: "Antigo Engenho de Viana — em análise", data: "Há 2 semanas" },
];
